config/routes.rb
Transitandtrails::Application.routes.draw do

  resources :favorites

  resources :identities

  class SslConstraint
    def self.matches?(request)
      !Rails.env.production? || request.ssl?
    end
  end

  class ApiSslConstraint
    def self.matches?(request)
      request.subdomain == 'api.rails' && !Rails.env.production? || request.ssl?
    end
  end

  constraints SslConstraint do
    constraints :subdomain => (Rails.env.production? ? /api\.staging|api\.rails|api/ : /.*/) do
      namespace :api, :defaults => {:format => :json} do
        namespace :v1 do
          resources :users, :only => [:show, :index]
          resources :attribute_categories, :only => [:show, :index]
          resources :trailheads, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
            end
          end
          resources :campgrounds, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
            end
          end
          resources :trips, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
              get 'route'
            end
          end
          resources :trailhead_attributes, :only => [:index]
          resources :campground_attributes, :only => [:index]
          resources :trip_attributes, :only => [:index]
        end
      end
    end
  end

  constraints :subdomain => (Rails.env.production? ? /embed\.rails|embed|rails/ : /.*/) do
    namespace :embed do
      match "login" => "sessions#new", :as => :sigin
      match "signin" => "sessions#new"
      match "signout" => "sessions#destroy", :as => :signout
      match "signup" => "registrations#new", :as => :signup
      match "confirm" => "registrations#confirm", :as => :confirm, :via => :get
      match "approve" => "registrations#approve", :as => :approve
      resources :trailheads do
        member do
          get 'details'
        end
      end
      resources :campgrounds do
        member do
          get 'details'
        end
      end
      resources :sessions, :only => [:new]
      resources :registrations, :only => [:new,:create]
      resources :parks, :only => [:show]
      resources :trips, :only => [:new,:create,:update,:edit,:show] do
        member do
          get 'edit_details'
          get 'edit_photos'
          get 'map'
          put 'update_details'
          put 'update_photos'
        end
      end
      match "plan/location" => "plan#location"
      match "plan/trailhead/:trailhead_id" => "plan#trailhead"
      match "plan/campground/:campground_id" => "plan#campground"
      match "plan/trip/:trip_id" => "plan#trip"
      match "plan/trailhead_list" => "plan#trailhead_list"
      match "plan/non_profit_partner_trailheads" => "plan#non_profit_partner_trailheads"
    end
  end

  resources :trips do
    resources :maps
    resources :photos
    resources :stories
    collection do
      post 'import_gpx'
      post 'import_kml'
      get 'near_address'
      get 'near_coordinates'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
    end
  end

  resources :campgrounds do
    resources :maps
    resources :photos
    resources :stories
    collection do
      get 'near_address'
      get 'near_coordinates'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
    end
  end

  resources :trailheads do
    resources :maps
    resources :photos
    resources :stories
    collection do
      post 'upload_kml'
      post 'import_trailheads'
      get 'near_address'
      get 'near_coordinates'
      get 'within_bounds'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
      get 'trip_editor_info_window'
      get 'transit_routers'
    end
  end

  match 'parks/autocomplete_park_name' => "parks#autocomplete_park_name", :as => :autocomplete_park_name_parks
  match 'parks(/:slug(/:county_slug))' => "parks#show"

  scope 'manage' do
    resources :parks do
      resources :maps, :only => [:index]
      resources :photos, :only => [:index]
      resources :trailheads, :only => [:index]
      resources :campgrounds, :only => [:index]
      collection do
        post 'upload_kml'
      end
    end
  end

  resources :stories

  resources :agencies do
    collection do
      get 'autocomplete_agency_name'
    end
  end

  resources :non_profit_partners do
    collection do
      get 'autocomplete_non_profit_partner_name'
    end
  end

  resources :partners, :only => [:index]

  match 'profile' => 'user_profiles#edit', :as => :profile

  resources :user_profiles do
    collection do
      get 'trailblazer_admin'
      get 'my_parks'
    end
    member do
      post 'reset_api_key'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  root :to => "application#landing"

  match "safari_cookie_set" => "application#safari_cookie_set"

  match "find" => "find#trips"

  match "find/trips" => "find#trips", :as => :find_trips

  match "find/trailheads" => "find#trailheads", :as => :find_trailheads

  match "find/campgrounds" => "find#campgrounds", :as => :find_campgrounds

  match "find/trailheads_within_bounds" => "find#trailheads_within_bounds"

  match "find/campgrounds_within_bounds" => "find#campgrounds_within_bounds"

  match "find/trips_within_bounds" => "find#trips_within_bounds"

  match 'objects/near/html' => 'find#objects_near'

  match 'find' => "find#find"

  match 'marinstage' => "find#marinstage"

  match 'find/marinstage' => "find#marinstage"

  match 'find/sanjosetrails' => "find#sanjosetrails"

  match 'find(/:region)' => "find#regional_landing_page"

  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get

  match 'geo/coordinates' => "geo#coordinates"

  match 'geo/distance_between' => "geo#distance_between"

  match 'session/loadkv' => "application#loadkv"
  match 'session/savekv' => "application#savekv"

  match 'plan/trailhead/:trailhead_id' => "plan#trailhead"
  match 'plan/trip/:trip_id' => "plan#trip", :as => :plan_trip
  match 'plan/campground/:campground_id' => "plan#campground"

end

app/controllers/find_controller.rb
class FindController < ApplicationController
  def trips
  end

  def trailheads
  end

  def campgrounds
  end

  def find
    @latest_photos = Photo.order('legacy_id desc, id desc').limit(6)
    @featuredtab = FeaturedTab.last
    @recentactivity = RecentActivity.last
  end

  def trailheads_within_bounds
    sw_latitude = Float(params[:sw_latitude])
    ne_latitude = Float(params[:ne_latitude])
    sw_longitude = Float(params[:sw_longitude])
    ne_longitude = Float(params[:ne_longitude])
    session[:starting_lat] = center_latitude = Float(params[:center_latitude])
    session[:starting_lng] = center_longitude = Float(params[:center_longitude])
    session[:starting_zoom] = zoom = Float(params[:zoom])
    offset = 0 || params[:offset]
    approved = true || params[:approved]
    @filter_names = []

    @trailheads = Trailhead.within_bounds(sw_latitude,sw_longitude,ne_latitude,ne_longitude)

    if(params[:only_mine])
      cookies[:only_mine] = true
      @trailheads = Trailhead.where(user_id: current_user.id)
      @filter_names += ["Only Mine"]
    else
      cookies.delete :only_mine
    end
      
    if(!params[:name_query].blank?)
      q = "%#{params[:name_query]}%"
      @trailheads = @trailheads.where("name ILIKE ?",q)
      @filter_names += ["Name: #{params[:name_query]}"]
    end


    if(params[:feature_ids])
      ids = params[:feature_ids]
      @trailheads = @trailheads.joins(:trailhead_features).where(:trailhead_features => {:id => ids}).group('trailheads.id').having(['count(trailheads.id) = ?',ids.length])
      @filter_names += TrailheadFeature.find(params[:feature_ids]).collect(&:name)
    end

    if(params[:unapproved])
      cookies[:unapproved] = true
      approved = false
      @filter_names += ["Unapproved"]
    else
      cookies.delete :unapproved
    end


    @near = "#{params[:near]}" || "San Francisco, CA"
    
    unless(params[:user_query].blank?)
      q = "%#{params[:user_query]}%"
      @users = User.where("username ILIKE ?",q)
      @trailheads = @trailheads.where(user_id: @users)
      @filter_names += ["User: #{params[:user_query]}"]
    end

    if params[:only_mine]
      @trailheads = Trailhead.where(approved: approved, id: @trailheads).near([center_latitude,center_longitude],1000)
    else
      @trailheads = Trailhead.where(approved: approved, id: @trailheads).near([center_latitude,center_longitude])
    end

    @trailheads = @trailheads.page params[:page]
    respond_to do |format|
      format.html { render :layout => false } # show.html.erb
      format.js # show.html.erb
      format.json { render json: @trailhead }
    end
  end

  def campgrounds_within_bounds
    sw_latitude = Float(params[:sw_latitude])
    ne_latitude = Float(params[:ne_latitude])
    sw_longitude = Float(params[:sw_longitude])
    ne_longitude = Float(params[:ne_longitude])
    session[:starting_lat] = center_latitude = Float(params[:center_latitude])
    session[:starting_lng] = center_longitude = Float(params[:center_longitude])
    session[:starting_zoom] = zoom = Float(params[:zoom])
    limit = 1000 || params[:limit]
    offset = 0 || params[:offset]
    approved = true || params[:approved]
    @filter_names = []

    @campgrounds = Campground.within_bounds(sw_latitude,sw_longitude,ne_latitude,ne_longitude)
    if(!params[:name_query].blank?)
      q = "%#{params[:name_query]}%"
      @campgrounds = Campground.where("name ILIKE ?",q)
      @filter_names += ["Name: #{params[:name_query]}"]
    end

    if(params[:only_mine])
      cookies[:only_mine] = true
      @campgrounds = Campground.where(user_id: current_user.id)
      @filter_names += ["Only Mine"]
    else
      cookies.delete :only_mine
    end


    if(params[:feature_ids])
      ids = params[:feature_ids]
      @campgrounds = @campgrounds.joins(:campground_features).where(:campground_features => {:id => ids}).group('campgrounds.id').having(['count(campgrounds.id) = ?',ids.length])
      @filter_names += CampgroundFeature.find(params[:feature_ids]).collect(&:name)
    end

    if(params[:unapproved])
      cookies[:unapproved] = true
      approved = false
      @filter_names += ["Unapproved"]
    else
      cookies.delete :unapproved
    end

    unless(params[:near].blank?)
      @filter_names += ["Near: #{params[:near]}"]
    end

    unless(params[:user_query].blank?)
      q = "%#{params[:user_query]}%"
      @users = User.where("username ILIKE ?",q)
      @campgrounds = @campgrounds.where(user_id: @users)
      @filter_names += ["User: #{params[:user_query]}"]
    end

    if params[:only_mine]
      @campgrounds = Campground.where(approved: approved, id: @campgrounds).near([center_latitude,center_longitude],1000)
    else
      @campgrounds = Campground.where(approved: approved, id: @campgrounds).near([center_latitude,center_longitude])
    end

    @campgrounds = @campgrounds.page params[:page]
    respond_to do |format|
      format.html { render :layout => false } # show.html.erb
      format.js # show.html.erb
      format.json { render json: @trailhead }
    end

  end

  def trips_within_bounds
    sw_latitude = Float(params[:sw_latitude])
    ne_latitude = Float(params[:ne_latitude])
    sw_longitude = Float(params[:sw_longitude])
    ne_longitude = Float(params[:ne_longitude])
    session[:starting_lat] = center_latitude = Float(params[:center_latitude])
    session[:starting_lng] = center_longitude = Float(params[:center_longitude])
    session[:starting_zoom] = zoom = Float(params[:zoom])
    approved = true || params[:approved]
    @filter_names = []
    search_radius = 10

    
    @trips = Trip.within_bounds(sw_latitude,sw_longitude,ne_latitude,ne_longitude)


    if(params[:only_mine])
      search_radius=1000
      cookies[:only_mine] = true
      @trips = Trip.where(user_id: current_user.id)
      @filter_names += ["Only Mine"]
    else
      cookies.delete :only_mine
    end

    if(!params[:name_query].blank?)
      q = "%#{params[:name_query]}%"
      @trips = Trip.where("name ILIKE ?",q)
      @filter_names += ["Name: #{params[:name_query]}"]
    end


    @near = params[:near].blank? ? "San Francisco, CA" : "#{params[:near]}"

    if(params[:duration_ids])
      @trips = @trips.where(duration_id: params[:duration_ids])
      @filter_names += Duration.find(params[:duration_ids]).collect(&:name)
    end

    if(params[:intensity_ids])
      @trips = @trips.where(intensity_id: params[:intensity_ids])
      @filter_names += Intensity.find(params[:intensity_ids]).collect(&:name)
    end

    if(params[:feature_ids])
      ids = params[:feature_ids]
      @trips = @trips.joins(:trip_features).where(:trip_features => {:id => ids}).group('trips.id').having(['count(trips.id) = ?',ids.length])
      @filter_names += TripFeature.find(params[:feature_ids]).collect(&:name)
    end

    if(params[:unapproved])
      cookies[:unapproved] = true
      approved = false
      @filter_names += ["Unapproved"]
    else
      cookies.delete :unapproved
    end

    unless(params[:user_query].blank?)
      q = "%#{params[:user_query]}%"
      @users = User.where("username ILIKE ?",q)
      @trips = @trips.where(user_id: @users)
      @filter_names += ["User: #{params[:user_query]}"]
    end

    if params[:only_mine]
      @trips = Trip.where(approved: approved, id: @trips).near([center_latitude,center_longitude],1000)
    else
      @trips = Trip.where(approved: approved, id: @trips).near([center_latitude,center_longitude])
    end

    @trips = @trips.page params[:page]
    respond_to do |format|
      format.html { render :layout => false } # show.html.erb
      format.js # show.html.erb
      format.json { render json: @trailhead }
    end

  end

  def objects_near
    latitude = params[:lat]
    longitude = params[:long]
    distance = params[:distance]
    approved = true
    limit = 1000
    offset = 0
    @trailheads = Trailhead.where(:approved => approved).near([latitude,longitude],distance).limit(limit).offset(offset)
    @campgrounds = Campground.where(:approved => approved).near([latitude,longitude],distance).limit(limit).offset(offset)
    @trips = Trip.where(:approved => approved).near([latitude,longitude],distance).limit(limit).offset(offset)

    if(params[:user_id])
      @trailheads = @trailheads.where(user_id: params[:user_id])
      @trips = @trips.where(user_id: params[:user_id])
      @campgrounds = @campgrounds.where(user_id: params[:user_id])
    end

    @allpoints = @trailheads + @campgrounds + @trips
    @allpoints.sort! { |a,b| Float(a.distance) <=> Float(b.distance) }
    render :layout => false
  end

  def marinstage
    self.find
    session[:starting_lat] = @starting_lat = 37.904141
    session[:starting_lng] = @starting_lng = -122.603838
    render "trips"
  end

  def sanjosetrails
    self.find
    session[:starting_lat] = @starting_lat = 37.3393857
    session[:starting_lng] = @starting_lng = -121.8949555
    render "trips"
  end

  def regional_landing_page
    self.find
    object = RegionalLandingPage.find_by_path(params[:region])
    if object.nil?
      raise ActionController::RoutingError.new('Not Found')
    end
    session[:starting_lat] = @starting_lat = object.latitude
    session[:starting_lng] = @starting_lng = object.longitude
    render "trips"
  end
end

app/views/find/_campground_filters.html.haml
%form#filters-form
  %p.filter-header
    Near
  %p
    %input.search-query#find-location{:placeholder => "Starting Address", :type => "text", :name => 'near'}
    %button.btn.btn-success.btn.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find
  %label.checkbox
    %input.filter-checkbox(type="checkbox" id="redo_search_in_map" value="true")
    Redo search in map
  - if user_signed_in?
    - only_mine = cookies[:only_mine] || false
    %label.checkbox
      - if only_mine
        %input.filter-checkbox(type="checkbox" name="only_mine" value="true" checked="true")  
      - else
        %input.filter-checkbox(type="checkbox" name="only_mine" value="true")          
      Only mine (#{current_user.username})
    - if can? :approve, Campground
      - unapproved = cookies[:unapproved] || false
      %label.checkbox
        - if unapproved
          %input.filter-checkbox(type="checkbox" name="unapproved" value="true" checked="true")
        - else
          %input.filter-checkbox(type="checkbox" name="unapproved" value="true")
        Unapproved

  %hr
  %p.filter-header
    Campground Name
  %p
    %input.search-query{:placeholder => "Type a campground name...", :type => "text", :name => 'name_query'}
    %button.btn.btn-success.btn.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find
  %hr
  %p.filter-header
    Author
  %p
    %input.search-query{:placeholder => "Type a user name...", :type => "text", :name => 'user_query'}
    %button.btn.btn-success.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find

  - Category.all.each do |category|
    - unless category.campground_features.empty?
      %hr
      %p.filter-header
        = category.name
      - category.campground_features.each do |feature|
        %label.checkbox
          %input.filter-checkbox(type="checkbox" name="feature_ids[]" value="#{feature.id}")
          = feature.name

app/views/find/_campgrounds_media_item.html.haml
%li.media.find-list-item(id="campground_list_item_#{campground.id}")
  .pull-left
    %a(href="#{campground_path(campground)}")
      %img.media-object.img-rounded.img-polaroid(src="#{campground.thumbnail_url}")
    %br
    = link_to "Zoom In", "#", :class => "btn btn-block zoom-button btn-warning btn-round"
    = link_to "Plan", "/plan/campground/#{campground.id}", :class => "btn btn-success btn-block btn-round"
    - if can? :edit, Campground
      = link_to edit_campground_path(campground), :class => "btn btn-primary btn-block  btn-round" do        
        Edit
    - if can? :approve, Campground
      - if campground.approved
        = link_to "Unapprove", unapprove_campground_path(campground), :method => :post, :class => "btn btn-warning btn-block btn-round", :remote =>  true
      - else
        = link_to "Approve", approve_campground_path(campground), :method => :post, :class => "btn btn-primary btn-block btn-round", :remote =>  true

    - if can? :destroy, Campground
      = link_to campground_path(campground), :method => :delete, :class => "btn btn-danger btn-block btn-round", :data => { :confirm => "Are you sure?" } do        
        Delete
  .media-body
    %a(href="#{campground_path(campground)}")
      %h4.media-heading
        = campground.name
    %p.park-name
      = campground.default_park_name
    = render :partial => "object_user_label", :locals => { :object => campground }
    %p.description
      = truncate_html(strip_tags(campground.description),:length=>300)
    .features
      - campground.categorized_attributes.each do |category,features|
        %p
          %span.category
            #{category}
          %br
          - features.each_with_index do |feature,index|
            - if index < 3
              %span.label.label-feature
                = feature.name
            - if index == 3
              = link_to "and more...", campground
%hr
:javascript
  Find.addCampgroundMarker(#{campground.as_json.except('description').to_json});

app/views/find/_object_user_label.html.haml
- if object.user
  %p
    - if object.user.profile.organization_avatar.file
      = image_tag object.user.profile.organization_avatar, :class => "img-rounded avatar"
    - else
      = image_tag object.user.profile.avatar, :class => "img-rounded avatar"
    = user_label(object.user)

app/views/find/_trailhead.html.haml
%li.media.find-list-item(id="trailhead_list_item_#{trailhead.id}")
  .pull-left
    %a(href="#{trailhead_path(trailhead)}")
      %img.media-object.img-rounded(src="#{trailhead.thumbnail_url}")
      %br

      = link_to "Zoom In", "#", :class => "btn btn-block zoom-button btn-success btn-round"
      - if current_user && (current_user.favorite_trailheads.include? trailhead)
        = link_to "Unfavorite", current_user.favorites.find_by_favorable_type_and_favorable_id("Trailhead",trailhead.id), :method=>:destroy, :class => "btn btn-success btn-block btn-round"
      - else
        = link_to "Favorite", favorites_path(:favorite => {:favorable_id=>trailhead.id,:favorable_type=>"Trailhead"}), :method=>:post, :class => "btn btn-success btn-block btn-round"
      = link_to "Plan My Trip", "/plan/trailhead/#{trailhead.id}", :class => "btn btn-success btn-block btn-round"
      - if can? :edit, trailhead
        = link_to "Edit Trailhead", edit_trailhead_path(trailhead), :class => "btn btn-primary btn-block btn-round"
      - if can? :destroy, trailhead
        = link_to "Delete Trailhead", trailhead_path(trailhead), :method => :delete, :class => "btn btn-danger btn-block btn-round", :data => { :confirm => "Are you sure?" }
  .media-body
    %a(href="#{trailhead_path(trailhead)}")
      %h4.media-heading.find-list-name
        = trailhead.name
    %p.park-name
      = trailhead.default_park_name
    = render :partial => "object_user_label", :locals => { :object => trailhead }

    %p.description
      = truncate_html(strip_tags(trailhead.description),:length=>300)
    .features
      - trailhead.categorized_attributes.each do |category,features|
        %p
          %span.category
            #{category}
          %br
          - features.each_with_index do |feature,index|
            - if index < 3
              %span.label.label-feature
                = feature.name
            - if index == 3
              = link_to "and more...", trailhead

app/views/find/_trailhead_filters.html.haml
%form#filters-form
  %p.filter-header
    Near
  %p
    %input.search-query#find-location{:placeholder => "Starting Address", :type => "text", :name => 'near'}
    %button.btn.btn-success.btn.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find
  %label.checkbox
    %input(type="checkbox" id="redo_search_in_map" value="true")
    Redo search in map
  - if user_signed_in?
    - only_mine = cookies[:only_mine] || false
    %label.checkbox
      - if only_mine
        %input.filter-checkbox(type="checkbox" name="only_mine" value="true" checked="true")  
      - else
        %input.filter-checkbox(type="checkbox" name="only_mine" value="true")          
      Only mine (#{current_user.username})
    - if can? :approve, Trip
      - unapproved = cookies[:unapproved] || false
      %label.checkbox
        - if unapproved
          %input.filter-checkbox(type="checkbox" name="unapproved" value="true" checked="true")
        - else
          %input.filter-checkbox(type="checkbox" name="unapproved" value="true")
        Unapproved

  %hr
  %p.filter-header
    Trailhead Name
  %p
    %input.search-query{:placeholder => "Type a trailhead name...", :type => "text", :name => 'name_query'}
    %button.btn.btn-success.btn.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find
  %hr
  %p.filter-header
    Author
  %p
    %input.search-query{:placeholder => "Type a user name...", :type => "text", :name => 'user_query'}
    %button.btn.btn-success.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find

  - Category.all.each do |category|
    - unless category.trailhead_features.empty?
      %hr
      %p.filter-header
        = category.name
      - category.trailhead_features.each do |feature|
        %label.checkbox
          %input.filter-checkbox(type="checkbox" name="feature_ids[]" value="#{feature.id}")
          = feature.name

app/views/find/_trip_filters.html.haml
%form#filters-form
  %p.filter-header
    Near
  %p
    %input.search-query#find-location{:placeholder => "Starting Address", :type => "text", :name => 'near'}
    %button.btn.btn-success.btn.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find
  %label.checkbox
    %input(type="checkbox" id="redo_search_in_map" value="true")
    Redo search in map
  - if user_signed_in?
    - only_mine = cookies[:only_mine] || false
    %label.checkbox
      - if only_mine
        %input.filter-checkbox(type="checkbox" name="only_mine" value="true" checked="true")  
      - else
        %input.filter-checkbox(type="checkbox" name="only_mine" value="true")          
      Only mine (#{current_user.username})
    - if can? :approve, Trip
      - unapproved = cookies[:unapproved] || false
      %label.checkbox
        - if unapproved
          %input.filter-checkbox(type="checkbox" name="unapproved" value="true" checked="true")
        - else
          %input.filter-checkbox(type="checkbox" name="unapproved" value="true")
        Unapproved

  %hr
  %p.filter-header
    Trip Name
  %p
    %input.search-query{:placeholder => "Type a trip name...", :type => "text", :name => 'name_query'}
    %button.btn.btn-success.btn.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find
  %hr
  %p.filter-header
    Duration
  %p
    - Duration.all.each do |d|
      %label.checkbox
        %input.filter-checkbox(type="checkbox" name="duration_ids[]" value="#{d.id}")
        = d.name
  %hr
  %p.filter-header
    Intensity
  %p
    - Intensity.all.each do |i|
      %label.checkbox
        %input.filter-checkbox(type="checkbox" name="intensity_ids[]" value="#{i.id}")
        = i.name
  %hr
  %p.filter-header
    Author
  %p
    %input.search-query{:placeholder => "Type a user name...", :type => "text", :name => 'user_query'}
    %button.btn.btn-success.btn-round.pull-right{:type => "submit", :value => "Find"}
      Find

  - Category.all.each do |category|
    - unless category.trip_features.empty?
      %hr
      %p.filter-header
        = category.name
      - category.trip_features.each do |feature|
        %label.checkbox
          %input.filter-checkbox(type="checkbox" name="feature_ids[]" value="#{feature.id}")
          = feature.name

app/views/find/_trips_media_item.html.haml
%li.media.find-list-item(id="trip_list_item_#{trip.id}")
  .pull-left
    %a(href="#{trip_path(trip)}")
      %img.media-object.img-rounded(src="#{trip.thumbnail_url}")
    %br
    = link_to "Zoom In", "#", :class => "btn btn-block zoom-button btn-warning btn-round"
    = link_to "Plan My Trip", "/plan/trip/#{trip.id}", :class => "btn btn-success btn-block btn-round"
    - if can? :edit, Trip
      = link_to "Edit", edit_trip_path(trip), :class => "btn btn-primary btn-block btn-round"
    - if can? :approve, Trip
      - if trip.approved
        = link_to "Unapprove", unapprove_trip_path(trip), :method => :post, :class => "btn btn-warning btn-block btn-round", :remote =>  true
      - else
        = link_to "Approve", approve_trip_path(trip), :method => :post, :class => "btn btn-primary btn-block btn-round", :remote =>  true
    - if can? :destroy, Trip
      = link_to "Delete Trip", trip_path(trip), :method => :delete, :class => "btn btn-danger btn-block btn-round", :data => { :confirm => "Are you sure?" }

  .media-body
    %a(href="#{trip_path(trip)}")
      %h4.media-heading.find-list-name
        = trip.name
    %p.park-name
      = trip.park_name
    = render :partial => "object_user_label", :locals => { :object => trip }
    / - if trip.user && trip.user.profile.organization_name
    /   %p
    /     = image_tag trip.user.profile.organization_avatar, :class => "img-rounded avatar"
    /     = organization_label(trip.user)

    %p
      .div(class="intensity-icon #{trip.intensity.name.downcase}")
      = trip.intensity.name
      |
      = trip.duration.name
      |
      = trip.length_miles.round(1)
      Miles
    %p.description
      = truncate_html(strip_tags(trip.description),:length=>200)
      = link_to "more", trip
    .features
      - trip.categorized_attributes.each do |category,features|
        %p
          %span.category
            #{category}
          %br
          - features.each_with_index do |feature,index|
            - if index < 3
              %span.label.label-feature
                = feature.name
            - if index == 3
              = link_to "and more...", trip
%hr
:javascript
  Find.addTripMarker(#{trip.as_json.except('geometry').except('route').except('description').to_json});

app/views/find/campgrounds.html.haml
:javascript
  find_mode = 'CAMPGROUNDS';
- content_for :list_filters do
  .list-header
    .list-header-icon.campgrounds
    %span.badge.badge-inverse#campground-count
      0
    Campgrounds Found
  .filters
    = render :partial => "campground_filters"