config/routes.rb
Transitandtrails::Application.routes.draw do

  resources :favorites

  resources :identities

  class SslConstraint
    def self.matches?(request)
      !Rails.env.production? || request.ssl?
    end
  end

  class ApiSslConstraint
    def self.matches?(request)
      request.subdomain == 'api.rails' && !Rails.env.production? || request.ssl?
    end
  end

  constraints SslConstraint do
    constraints :subdomain => (Rails.env.production? ? /api\.staging|api\.rails|api/ : /.*/) do
      namespace :api, :defaults => {:format => :json} do
        namespace :v1 do
          resources :users, :only => [:show, :index]
          resources :attribute_categories, :only => [:show, :index]
          resources :trailheads, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
            end
          end
          resources :campgrounds, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
            end
          end
          resources :trips, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
              get 'route'
            end
          end
          resources :trailhead_attributes, :only => [:index]
          resources :campground_attributes, :only => [:index]
          resources :trip_attributes, :only => [:index]
        end
      end
    end
  end

  constraints :subdomain => (Rails.env.production? ? /embed\.rails|embed|rails/ : /.*/) do
    namespace :embed do
      match "login" => "sessions#new", :as => :sigin
      match "signin" => "sessions#new"
      match "signout" => "sessions#destroy", :as => :signout
      match "signup" => "registrations#new", :as => :signup
      match "confirm" => "registrations#confirm", :as => :confirm, :via => :get
      match "approve" => "registrations#approve", :as => :approve
      resources :trailheads do
        member do
          get 'details'
        end
      end
      resources :campgrounds do
        member do
          get 'details'
        end
      end
      resources :sessions, :only => [:new]
      resources :registrations, :only => [:new,:create]
      resources :parks, :only => [:show]
      resources :trips, :only => [:new,:create,:update,:edit,:show] do
        member do
          get 'edit_details'
          get 'edit_photos'
          get 'map'
          put 'update_details'
          put 'update_photos'
        end
      end
      match "plan/location" => "plan#location"
      match "plan/trailhead/:trailhead_id" => "plan#trailhead"
      match "plan/campground/:campground_id" => "plan#campground"
      match "plan/trip/:trip_id" => "plan#trip"
      match "plan/trailhead_list" => "plan#trailhead_list"
      match "plan/non_profit_partner_trailheads" => "plan#non_profit_partner_trailheads"
    end
  end

  resources :trips do
    resources :maps
    resources :photos
    resources :stories
    collection do
      post 'import_gpx'
      post 'import_kml'
      get 'near_address'
      get 'near_coordinates'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
    end
  end

  resources :campgrounds do
    resources :maps
    resources :photos
    resources :stories
    collection do
      get 'near_address'
      get 'near_coordinates'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
    end
  end

  resources :trailheads do
    resources :maps
    resources :photos
    resources :stories
    collection do
      post 'upload_kml'
      post 'import_trailheads'
      get 'near_address'
      get 'near_coordinates'
      get 'within_bounds'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
      get 'trip_editor_info_window'
      get 'transit_routers'
    end
  end

  match 'parks/autocomplete_park_name' => "parks#autocomplete_park_name", :as => :autocomplete_park_name_parks
  match 'parks(/:slug(/:county_slug))' => "parks#show"

  scope 'manage' do
    resources :parks do
      resources :maps, :only => [:index]
      resources :photos, :only => [:index]
      resources :trailheads, :only => [:index]
      resources :campgrounds, :only => [:index]
      collection do
        post 'upload_kml'
      end
    end
  end

  resources :stories

  resources :agencies do
    collection do
      get 'autocomplete_agency_name'
    end
  end

  resources :non_profit_partners do
    collection do
      get 'autocomplete_non_profit_partner_name'
    end
  end

  resources :partners, :only => [:index]

  match 'profile' => 'user_profiles#edit', :as => :profile

  resources :user_profiles do
    collection do
      get 'trailblazer_admin'
      get 'my_parks'
    end
    member do
      post 'reset_api_key'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  root :to => "application#landing"

  match "safari_cookie_set" => "application#safari_cookie_set"

  match "find" => "find#trips"

  match "find/trips" => "find#trips", :as => :find_trips

  match "find/trailheads" => "find#trailheads", :as => :find_trailheads

  match "find/campgrounds" => "find#campgrounds", :as => :find_campgrounds

  match "find/trailheads_within_bounds" => "find#trailheads_within_bounds"

  match "find/campgrounds_within_bounds" => "find#campgrounds_within_bounds"

  match "find/trips_within_bounds" => "find#trips_within_bounds"

  match 'objects/near/html' => 'find#objects_near'

  match 'find' => "find#find"

  match 'marinstage' => "find#marinstage"

  match 'find/marinstage' => "find#marinstage"

  match 'find/sanjosetrails' => "find#sanjosetrails"

  match 'find(/:region)' => "find#regional_landing_page"

  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get

  match 'geo/coordinates' => "geo#coordinates"

  match 'geo/distance_between' => "geo#distance_between"

  match 'session/loadkv' => "application#loadkv"
  match 'session/savekv' => "application#savekv"

  match 'plan/trailhead/:trailhead_id' => "plan#trailhead"
  match 'plan/trip/:trip_id' => "plan#trip", :as => :plan_trip
  match 'plan/campground/:campground_id' => "plan#campground"

end

app/controllers/api/v1/campgrounds_controller.rb
module Api
  module V1
    class CampgroundsController < Api::V1::ApiController

      caches_action :index, :expires_in => 60, :cache_path => Proc.new { |c| c.params.except(:key) }

      def index
        @campgrounds = Campground.order("id").includes(:cached_park_by_bounds,:park)
        if params[:non_profit_partner_id]
          partner_id = params[:non_profit_partner_id]
          parks = Park.where(:non_profit_partner_id => partner_id)
          campground_ids = parks.collect{|p| p.campgrounds }.flatten

          attribute_id = params[:attribute_id]
          if attribute_id
            @campgrounds = CampgroundFeature.find(attribute_id).campgrounds.where(id:campground_ids).order("id")
          else
            @campgrounds = Campground.where(id:campground_ids).order("id")
          end
        end

        if(params[:latitude] && params[:longitude])
          distance = params[:distance] || 100
          if distance.to_i < 100
            @campgrounds = @campgrounds.near([params[:latitude],params[:longitude]],distance)
          end
        end

        if(params[:user_id])
          @campgrounds = @campgrounds.where(user_id:params[:user_id].split(','))
        end


        @campgrounds = apply_limit_and_offset(params,@campgrounds.order('id'))
      end

      def show
        @campground = Campground.find(params[:id])
      end

      def photos
        @photos = Campground.find(params[:id]).photos
      end

      def maps
        @maps = Campground.find(params[:id]).maps
      end

      def attributes
        @attributes = Campground.find(params[:id]).campground_features
      end

    end
  end
end

app/controllers/campgrounds_controller.rb
class CampgroundsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index,:show,:near_coordinates,:info_window]

  # GET /campgrounds
  # GET /campgrounds.json
  def index
    redirect_to find_campgrounds_path
  end

  def approve
    @campground = Campground.find(params[:id])
    @campground.update_attributes(approved:true)
  end

  def unapprove
    @campground = Campground.find(params[:id])
    @campground.update_attributes(approved:false)
  end

  # GET /campgrounds/near_coordinates
  # GET /campgrounds/near_coordinates.json
  def near_coordinates
    latitude = params[:latitude] || 37.7749295
    longitude = params[:longitude] || -122.4194155
    distance = params[:distance] || 10
    limit = 1000 || params[:limit]
    offset = 0 || params[:offset]
    approved = true || params[:approved]
    @campgrounds = Campground.where(:approved => approved).near([latitude,longitude],distance).limit(limit).offset(offset)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campgrounds }
    end
  end

  def info_window
    @point = Campground.find(params[:id])
    @feature_names = @point.campground_features.collect{|f| f.name}.join(",  ")
    respond_to do |format|
      format.html { render :layout => false} # show.html.erb
    end
  end


  # GET /campgrounds/1
  # GET /campgrounds/1.json
  def show
    if request.referer =~ /\/embed\/parks/ && request.format == 'html'
      redirect_to "/embed" + request.path
      return
    end
    
    @campground = Campground.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campground }
    end
  end

  # GET /campgrounds/new
  # GET /campgrounds/new.json
  def new
    @campground = Campground.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campground }
    end
  end

  # GET /campgrounds/1/edit
  def edit
    @campground = Campground.find(params[:id])
  end

  # POST /campgrounds
  # POST /campgrounds.json
  def create
    @campground = Campground.new(params[:campground])
    @campground.user = current_user

    respond_to do |format|
      if @campground.save
        format.html { redirect_to @campground, notice: 'Campground was successfully created.' }
        format.json { render json: @campground, status: :created, location: @campground }
      else
        format.html { render action: "new" }
        format.json { render json: @campground.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campgrounds/1
  # PUT /campgrounds/1.json
  def update
    @campground = Campground.find(params[:id])

    respond_to do |format|
      if @campground.update_attributes(params[:campground])
        format.html { redirect_to @campground, notice: 'Campground was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campground.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campgrounds/1
  # DELETE /campgrounds/1.json
  def destroy
    @campground = Campground.find(params[:id])
    @campground.destroy

    respond_to do |format|
      format.html { redirect_to find_campgrounds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/embed/campgrounds_controller.rb
module Embed
  class CampgroundsController < ApplicationController
    def show
      @campground = Campground.find(params[:id])

      if params[:show]
        @show = params[:show].split(',')
      else
        @show = ['trails','description','contributor','summary','photos','map','attributes','actions','header','downloads','branding','nonprofit_partner']
      end

      if params[:hide]
        @hide = params[:hide].split(',')
        @show = @show - @hide
      end

      if params[:hide_title]
        @hide_title = params[:hide_title] == 'true'
      end

      if params[:hide_section_labels]
        @hide_section_labels = params[:hide_section_labels] == 'true'
      end

      if params[:full_description]
        @full_description = params[:full_description] == 'true'
      end

      render :layout => "embed/responsive"
    end

    def details
      @campground = Campground.find(params[:id])
      render "details", :layout => "embed"
    end
  end
end

app/controllers/embed/parks_controller.rb
module Embed
  class ParksController < ApplicationController
    def show
      if params[:hide_title]
        @hide_title = params[:hide_title] == 'true'
      end

      if params[:county_slug]
        @parks = Park.where(:slug=>params[:slug],:county_slug=>params[:county_slug])
      elsif params[:slug]
        @parks = Park.where(:slug=>params[:slug])
        if @parks.empty?
           @parks = Park.where(:id=>params[:slug])
        end
      elsif params[:id]
          @parks = Park.where(:id=>params[:id])
      end      

      @polys = []
      @acres = 0
      @agencies = []
      @names = []
      @trips = []
      @tripnames = []
      @trailheads = []
      @trailheadnames = []
      @campgrounds = []
      @campgroundnames = []

      @agencies = @parks.collect{|p| p.agency}.uniq.compact

      @parks.each do |park|
        @acres += (park.acres || 0)
        @polys += park.polys
        @trips += park.trips
        @campgrounds += park.campgrounds
        @trailheads += park.trailheads
      end

      @trips.uniq!
      @campgrounds.uniq!
      @park = @parks && @parks.first
      render :layout => "embed/responsive"

    end
  end
end

app/controllers/embed/plan_controller.rb
module Embed
  class PlanController < ApplicationController
    before_filter :width_filter, :display_params
    caches_action :non_profit_partner_trailheads, :expires_in => 60, :cache_path => Proc.new { |c| c.params }

    def width_filter
      if params[:width]
        @width_class = "width" + params[:width]
      end
    end

    def display_params
      if params[:hide_title]
        @hide_title = params[:hide_title] == 'true'
      end
    end

    def plan
      @initial_date = params[:date]
      @arrive = params[:arrive]
      render "plan", :layout => "embed"
    end

    def location
      @selected_location = true
      @destination_name = params[:destination_name]
      @latitude = params[:lat]
      @longitude = params[:lng]
      plan
    end

    def trailhead
      @selected_trailhead = Trailhead.find(params[:trailhead_id])
      plan
    end

    def campground
      @selected_campground = Campground.find(params[:campground_id])
      plan
    end

    def trip
      @selected_trip = Trip.find(params[:trip_id])
      plan
    end

    def trailhead_list
      trailhead_ids = params[:trailhead_ids].split(',')
      @selected_trailheads = Trailhead.where(id: trailhead_ids).order('name')
      plan
    end

    def non_profit_partner_trailheads
      partner_id = params[:partner_id]
      parks = Park.where(:non_profit_partner_id => partner_id)
      trailhead_ids = parks.collect{|p| p.trailheads }.flatten
      trailhead_ids += Trailhead.where(non_profit_partner_id: partner_id)
      attribute_id = params[:attribute_id]
      if attribute_id
        @selected_trailheads = TrailheadFeature.find(attribute_id).trailheads.where(id:trailhead_ids)
      else
        @selected_trailheads = Trailhead.where(id:trailhead_ids)
      end
      @selected_trailheads = @selected_trailheads.order('name')
      plan
    end

  end
end

app/controllers/embed/registrations_controller.rb
module Embed
  class RegistrationsController < ApplicationController
    before_filter :embed_authenticate_admin!, :only => [:approve]

    def new
      @user = User.new
      render :layout => 'static_embed'
    end

    # POST /trailheads
    # POST /trailheads.json
    def create
      @user = User.new(params[:user])
      @user.build_user_profile(signup_source:"bay_nature_trip_editor")
      respond_to do |format|
        if @user.save
          format.html { render "thanks", :layout => "static_embed" }
        else
          format.html { render action: "new", :layout => 'static_embed' }
        end
      end
    end

    def approve
      @user = User.find_by_username(params[:username])
      @user.trailblazer = true
      @user.add_role :baynature_trailblazer
      respond_to do |format|
        if @user.save
          Embed::RegistrationMailer.user_approved_email(@user).deliver
          format.html { render :layout => "static_embed" }
        else
          format.html { render :layout => "static_embed" }
        end
      end
    end

    def confirm
      @user = User.confirm_by_token(params[:confirmation_token])
      if(@user.confirmed?)
        Embed::RegistrationMailer.admin_registration_email(@user).deliver
      end
      render :layout => "static_embed"
    end

  end
end

app/controllers/embed/sessions_controller.rb
module Embed
  class SessionsController < ApplicationController
    skip_before_filter :verify_authenticity_token
    def new
      render "new", :layout => "static_embed"
    end

    def destroy
      sign_out
      redirect_to embed_signin_path
    end
  end
end

app/helpers/campgrounds_helper.rb
module CampgroundsHelper
end

app/views/embed/campgrounds/details.html.haml
- content_for :head do
  = javascript_include_tag "application"
  = javascript_include_tag "legacy/common"

  = stylesheet_link_tag "application"
  = stylesheet_link_tag "legacy/legacy"
  = stylesheet_link_tag "legacy/campground_detail"
  %script{:src => "/assets/legacy/jquery/js/jquery.tools.min.js", :type => "text/javascript"}

- content_for :page_title do
  Campground Details

- content_for :page_content do
  #page.trip-details.legacy

    #trail-details.trail-details-overlay
      != @campground.description

    #details-section
      #plan.alt.trailhead
        / e: page head
        #trip-meta
          .header
            %h2 #{@campground.name}
            %img.type-flag{:alt => "", :src => "/assets/legacy/campground.png"}/
            - if @campground.default_park
              %em
              %a{:href => "#{park_path(@campground.default_park)}"} #{@campground.default_park.name}
          / b:details
          #trailhead-details
            - if @campground.description
              .description
                != truncate_html(@campground.description, :length=> 300,  :omission => '...<br/><a class="trail-details-modal modal" rel="#trail-details" >Read more...</a>')
              / e: entry
            - else
              %div{:style => "height:10px"}

            = render :partial => "/shared/partials/features", :locals => {:object=>@campground}

            .button-frame

              %a.green-button.padded-sides{:href => "/embed/plan/campground/#{@campground.id}"}
                Plan Trip to Here

            - if can?(:edit,@campground)
              .button-frame
                %a.green-button{:href => "#{edit_campground_path(@campground)}", :target => "_blank"} Edit Campground

            - if can?(:destroy,@campground)
              .button-frame
                = link_to("Delete Campground", @campground, :method => :delete, :confirm => "Are you sure?", :class=>"green-button")

            = render :partial => "/shared/partials/object_maps", :locals => {:object=>@campground}

          = render :partial => "/shared/partials/agency", :locals => {:object=>@campground}

        = render :partial => "/shared/partials/non_profit_partner", :locals => {:object=>@campground}

  :javascript
    $(function(){
      $("a.modal").overlay();
    });

app/views/embed/campgrounds/show.html.haml
- content_for :page_title do
  = params[:title] || "Campground"

- content_for :page_content do

  .content
    - if @show.include? 'header'
      .header
        %img.type-flag{:alt => "", :src => "/assets/legacy/campground.png"}/
        .trip-name
          = @campground.name
        - if @campground.default_park
          %em
          = @campground.default_park.name

    - if @show.include? 'contributor'
      .contributor.embed-section
        - unless @hide_section_labels
          %label.feature
            Contributed By

        = render :partial => "/embed/trips/contributor", :locals => {:object=>@campground}
        %br
        = render :partial => "/shared/partials/agency", :locals => {:object=>@campground}


    - if (@show.include? 'description') && !@campground.description.blank?
      .description.embed-section
        - unless @hide_section_labels
          %label.feature
            Description

        - if @full_description
          != @campground.description
        - else
          .short-description
            != truncate_html(@campground.description, :length=> 400,  :omission => " ...<p><br/><a id='more-desc-link' class='read-more-less-link' href='#'>Read more &raquo;</a></p>")
          .full-description
            != @campground.description
            %br
            = link_to "#", id: "less-desc-link", class: "read-more-less-link" do
              &laquo; Read Less

    - if @show.include? 'actions'
      .summary.embed-section
        / - unless @hide_section_labels
        /   %label.feature
        /     Plan
        / %a.green-button.padded-sides{:href => "/embed/plan/trip/#{@trip.id}"}
        /   Plan Your Trip!
        %iframe#plan-embed(src="/embed/plan/campground/#{@campground.id}?hide_title=true")


    - if (@show.include? 'photos') && !@campground.photos.empty?
      .photos.embed-section
        - unless @hide_section_labels
          %label.feature
            Photos
        = render :partial => "/shared/partials/photo_carousel", :locals => {:object=>@campground}

    / - if @show.include? 'map'
    - if false
      / %script(src="//maps.googleapis.com/maps/api/js?key=AIzaSyCcUhpQftpOwXVSLJqHrvwYCqnhTy3bchE&sensor=false&libraries=drawing,geometry")

      %script{:src => "/assets/legacy/pointmap.js", :type => "text/javascript"}

      :javascript
        $(function(){
          initTrailheadDetails(#{@campground.id}, false);

        });

      .route-map.embed-section
        - unless @hide_section_labels
          %label.feature
            Map
        #plan-map.trailhead-details-map

    - if @show.include? 'attributes' && !@campground.campground_features.empty?
      .features.embed-section
        = render :partial => "/shared/partials/features", :locals => {:object=>@campground}

    - if (@show.include? 'downloads') && !@campground.maps.empty?
      .map-downloads.embed-section
        - unless @hide_section_labels
          %label.feature
            Downloads
        = render :partial => "/embed/trips/downloads", :locals => {:object=>@campground}

    - regional_trails = @campground.campground_features.where(:category_id=>Category.where(:name=>"Regional Trail"))

    - if @show.include? 'trails' && !regional_trails.empty?
      .regional-trails.embed-section
        - unless @hide_section_labels
          %label.feature
            Regional Trails

        - regional_trails.each do |feature|
          - klass = feature == regional_trails.last ? "agency last" : "agency"
          .if.endif{:class => "#{klass}"}
            .logo
              - if feature.marker_icon
                - if feature.link_url
                  %a{:href => "#{feature.link_url}", :target => "_blank"}
                    %img{:src => "#{feature.marker_icon.url}"}/
                - else
                  %img{:src => "#{feature.marker_icon.url}"}/
            .text
              This campground is part of the
              .name
                - if feature.link_url
                  %a{:href => "#{feature.link_url}", :target => "_blank"}
                    #{ feature.name }
                - else
                  #{feature.name}

    - if @show.include? "nonprofit_partner" && (@campground.respond_to?(:non_profit_partner) && @campground.non_profit_partner)
      .noprofit-partner.embed-section
        = render :partial => "/shared/partials/non_profit_partner", :locals => {:object=>@campground}

    - if request.referer =~ /\/embed\/parks/
      .actions.embed-section
        %a.green-button.padded-sides{:href => "#{request.referer}"}
          &laquo; Back

    .visit-tnt.embed-section
      = link_to "View this Campground at Transit & Trails", campground_url(@campground,:host=>"www.transitandtrails.org"), :target => "_blank"

  = javascript_include_tag "embed"

  :javascript
    $(function(){
      $('a.trailhead').attr('target','_blank');
    });