config/routes.rb
Transitandtrails::Application.routes.draw do

  resources :favorites

  resources :identities

  class SslConstraint
    def self.matches?(request)
      !Rails.env.production? || request.ssl?
    end
  end

  class ApiSslConstraint
    def self.matches?(request)
      request.subdomain == 'api.rails' && !Rails.env.production? || request.ssl?
    end
  end

  constraints SslConstraint do
    constraints :subdomain => (Rails.env.production? ? /api\.staging|api\.rails|api/ : /.*/) do
      namespace :api, :defaults => {:format => :json} do
        namespace :v1 do
          resources :users, :only => [:show, :index]
          resources :attribute_categories, :only => [:show, :index]
          resources :trailheads, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
            end
          end
          resources :campgrounds, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
            end
          end
          resources :trips, :only => [:show, :index] do
            member do
              get 'photos'
              get 'attributes'
              get 'maps'
              get 'route'
            end
          end
          resources :trailhead_attributes, :only => [:index]
          resources :campground_attributes, :only => [:index]
          resources :trip_attributes, :only => [:index]
        end
      end
    end
  end

  constraints :subdomain => (Rails.env.production? ? /embed\.rails|embed|rails/ : /.*/) do
    namespace :embed do
      match "login" => "sessions#new", :as => :sigin
      match "signin" => "sessions#new"
      match "signout" => "sessions#destroy", :as => :signout
      match "signup" => "registrations#new", :as => :signup
      match "confirm" => "registrations#confirm", :as => :confirm, :via => :get
      match "approve" => "registrations#approve", :as => :approve
      resources :trailheads do
        member do
          get 'details'
        end
      end
      resources :campgrounds do
        member do
          get 'details'
        end
      end
      resources :sessions, :only => [:new]
      resources :registrations, :only => [:new,:create]
      resources :parks, :only => [:show]
      resources :trips, :only => [:new,:create,:update,:edit,:show] do
        member do
          get 'edit_details'
          get 'edit_photos'
          get 'map'
          put 'update_details'
          put 'update_photos'
        end
      end
      match "plan/location" => "plan#location"
      match "plan/trailhead/:trailhead_id" => "plan#trailhead"
      match "plan/campground/:campground_id" => "plan#campground"
      match "plan/trip/:trip_id" => "plan#trip"
      match "plan/trailhead_list" => "plan#trailhead_list"
      match "plan/non_profit_partner_trailheads" => "plan#non_profit_partner_trailheads"
    end
  end

  resources :trips do
    resources :maps
    resources :photos
    resources :stories
    collection do
      post 'import_gpx'
      post 'import_kml'
      get 'near_address'
      get 'near_coordinates'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
    end
  end

  resources :campgrounds do
    resources :maps
    resources :photos
    resources :stories
    collection do
      get 'near_address'
      get 'near_coordinates'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
    end
  end

  resources :trailheads do
    resources :maps
    resources :photos
    resources :stories
    collection do
      post 'upload_kml'
      post 'import_trailheads'
      get 'near_address'
      get 'near_coordinates'
      get 'within_bounds'
    end
    member do
      post 'approve'
      post 'unapprove'
      get 'info_window'
      get 'trip_editor_info_window'
      get 'transit_routers'
    end
  end

  match 'parks/autocomplete_park_name' => "parks#autocomplete_park_name", :as => :autocomplete_park_name_parks
  match 'parks(/:slug(/:county_slug))' => "parks#show"

  scope 'manage' do
    resources :parks do
      resources :maps, :only => [:index]
      resources :photos, :only => [:index]
      resources :trailheads, :only => [:index]
      resources :campgrounds, :only => [:index]
      collection do
        post 'upload_kml'
      end
    end
  end

  resources :stories

  resources :agencies do
    collection do
      get 'autocomplete_agency_name'
    end
  end

  resources :non_profit_partners do
    collection do
      get 'autocomplete_non_profit_partner_name'
    end
  end

  resources :partners, :only => [:index]

  match 'profile' => 'user_profiles#edit', :as => :profile

  resources :user_profiles do
    collection do
      get 'trailblazer_admin'
      get 'my_parks'
    end
    member do
      post 'reset_api_key'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  root :to => "application#landing"

  match "safari_cookie_set" => "application#safari_cookie_set"

  match "find" => "find#trips"

  match "find/trips" => "find#trips", :as => :find_trips

  match "find/trailheads" => "find#trailheads", :as => :find_trailheads

  match "find/campgrounds" => "find#campgrounds", :as => :find_campgrounds

  match "find/trailheads_within_bounds" => "find#trailheads_within_bounds"

  match "find/campgrounds_within_bounds" => "find#campgrounds_within_bounds"

  match "find/trips_within_bounds" => "find#trips_within_bounds"

  match 'objects/near/html' => 'find#objects_near'

  match 'find' => "find#find"

  match 'marinstage' => "find#marinstage"

  match 'find/marinstage' => "find#marinstage"

  match 'find/sanjosetrails' => "find#sanjosetrails"

  match 'find(/:region)' => "find#regional_landing_page"

  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get

  match 'geo/coordinates' => "geo#coordinates"

  match 'geo/distance_between' => "geo#distance_between"

  match 'session/loadkv' => "application#loadkv"
  match 'session/savekv' => "application#savekv"

  match 'plan/trailhead/:trailhead_id' => "plan#trailhead"
  match 'plan/trip/:trip_id' => "plan#trip", :as => :plan_trip
  match 'plan/campground/:campground_id' => "plan#campground"

end

app/models/campground.rb
require "point_of_interest"

class Campground < ActiveRecord::Base
  include PointOfInterest

  belongs_to :user
  belongs_to :park
  belongs_to :agency_override, :class_name => "Agency", :foreign_key => "agency_id"
  belongs_to :cached_park_by_bounds, :class_name => "Park", :foreign_key => "cached_park_by_bounds_id"
  has_many :maps, :as => :mapable, :dependent => :destroy
  has_many :photos, :as => :photoable, :dependent => :destroy
  has_many :stories, :as => :storytellable, :dependent => :destroy
  
  scope :approved, where(:approved => true)
  
  has_and_belongs_to_many :campground_features
  attr_accessible :approved,
                  :description,
                  :latitude,
                  :longitude,
                  :name,
                  :campground_feature_ids,
                  :agency_id,
                  :user_id,
                  :cached_park_by_bounds_id
  reverse_geocoded_by :latitude, :longitude

  validates :name, :presence => true, :uniqueness => true

  before_save :park_by_bounds

  before_create :auto_approve
  has_paper_trail
  
  after_save :touch_park

  def touch_park
    default_park.touch if default_park
    park.touch if park
  end
  
  def categorized_attributes
    result = {}
    self.campground_features.includes(:category).each do |feature|
      if result[feature.category.name]
        result[feature.category.name] << feature
      else
        result[feature.category.name] = [feature]
      end
    end

    # Category.all.each do |category|
    #   features = self.campground_features.where(:category_id=>category.id).order("id")
    #   if features.count > 0
    #     result[category.name] = features
    #   end
    # end
    result
  end

  def thumbnail_url
    if self.photos.first
      self.photos.first.flickr_large_square_url
    else
      "/assets/placeholder_item_image.png"
    end
  end

  def self.within_bounds(sw_latitude,sw_longitude,ne_latitude,ne_longitude)
    min_latitude = sw_latitude
    max_latitude = ne_latitude
    min_longitude = sw_longitude
    max_longitude = ne_longitude
    self.where("latitude > :min_latitude AND latitude < :max_latitude AND longitude > :min_longitude AND longitude < :max_longitude",
      :min_latitude => min_latitude, :min_longitude => min_longitude, :max_latitude => max_latitude, :max_longitude => max_longitude)
  end


end

app/controllers/api/v1/campgrounds_controller.rb
module Api
  module V1
    class CampgroundsController < Api::V1::ApiController

      caches_action :index, :expires_in => 60, :cache_path => Proc.new { |c| c.params.except(:key) }

      def index
        @campgrounds = Campground.order("id").includes(:cached_park_by_bounds,:park)
        if params[:non_profit_partner_id]
          partner_id = params[:non_profit_partner_id]
          parks = Park.where(:non_profit_partner_id => partner_id)
          campground_ids = parks.collect{|p| p.campgrounds }.flatten

          attribute_id = params[:attribute_id]
          if attribute_id
            @campgrounds = CampgroundFeature.find(attribute_id).campgrounds.where(id:campground_ids).order("id")
          else
            @campgrounds = Campground.where(id:campground_ids).order("id")
          end
        end

        if(params[:latitude] && params[:longitude])
          distance = params[:distance] || 100
          if distance.to_i < 100
            @campgrounds = @campgrounds.near([params[:latitude],params[:longitude]],distance)
          end
        end

        if(params[:user_id])
          @campgrounds = @campgrounds.where(user_id:params[:user_id].split(','))
        end


        @campgrounds = apply_limit_and_offset(params,@campgrounds.order('id'))
      end

      def show
        @campground = Campground.find(params[:id])
      end

      def photos
        @photos = Campground.find(params[:id]).photos
      end

      def maps
        @maps = Campground.find(params[:id]).maps
      end

      def attributes
        @attributes = Campground.find(params[:id]).campground_features
      end

    end
  end
end

app/controllers/campgrounds_controller.rb
class CampgroundsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index,:show,:near_coordinates,:info_window]

  # GET /campgrounds
  # GET /campgrounds.json
  def index
    redirect_to find_campgrounds_path
  end

  def approve
    @campground = Campground.find(params[:id])
    @campground.update_attributes(approved:true)
  end

  def unapprove
    @campground = Campground.find(params[:id])
    @campground.update_attributes(approved:false)
  end

  # GET /campgrounds/near_coordinates
  # GET /campgrounds/near_coordinates.json
  def near_coordinates
    latitude = params[:latitude] || 37.7749295
    longitude = params[:longitude] || -122.4194155
    distance = params[:distance] || 10
    limit = 1000 || params[:limit]
    offset = 0 || params[:offset]
    approved = true || params[:approved]
    @campgrounds = Campground.where(:approved => approved).near([latitude,longitude],distance).limit(limit).offset(offset)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campgrounds }
    end
  end

  def info_window
    @point = Campground.find(params[:id])
    @feature_names = @point.campground_features.collect{|f| f.name}.join(",  ")
    respond_to do |format|
      format.html { render :layout => false} # show.html.erb
    end
  end


  # GET /campgrounds/1
  # GET /campgrounds/1.json
  def show
    if request.referer =~ /\/embed\/parks/ && request.format == 'html'
      redirect_to "/embed" + request.path
      return
    end
    
    @campground = Campground.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campground }
    end
  end

  # GET /campgrounds/new
  # GET /campgrounds/new.json
  def new
    @campground = Campground.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campground }
    end
  end

  # GET /campgrounds/1/edit
  def edit
    @campground = Campground.find(params[:id])
  end

  # POST /campgrounds
  # POST /campgrounds.json
  def create
    @campground = Campground.new(params[:campground])
    @campground.user = current_user

    respond_to do |format|
      if @campground.save
        format.html { redirect_to @campground, notice: 'Campground was successfully created.' }
        format.json { render json: @campground, status: :created, location: @campground }
      else
        format.html { render action: "new" }
        format.json { render json: @campground.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campgrounds/1
  # PUT /campgrounds/1.json
  def update
    @campground = Campground.find(params[:id])

    respond_to do |format|
      if @campground.update_attributes(params[:campground])
        format.html { redirect_to @campground, notice: 'Campground was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campground.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campgrounds/1
  # DELETE /campgrounds/1.json
  def destroy
    @campground = Campground.find(params[:id])
    @campground.destroy

    respond_to do |format|
      format.html { redirect_to find_campgrounds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/embed/campgrounds_controller.rb
module Embed
  class CampgroundsController < ApplicationController
    def show
      @campground = Campground.find(params[:id])

      if params[:show]
        @show = params[:show].split(',')
      else
        @show = ['trails','description','contributor','summary','photos','map','attributes','actions','header','downloads','branding','nonprofit_partner']
      end

      if params[:hide]
        @hide = params[:hide].split(',')
        @show = @show - @hide
      end

      if params[:hide_title]
        @hide_title = params[:hide_title] == 'true'
      end

      if params[:hide_section_labels]
        @hide_section_labels = params[:hide_section_labels] == 'true'
      end

      if params[:full_description]
        @full_description = params[:full_description] == 'true'
      end

      render :layout => "embed/responsive"
    end

    def details
      @campground = Campground.find(params[:id])
      render "details", :layout => "embed"
    end
  end
end

app/helpers/campgrounds_helper.rb
module CampgroundsHelper
end

app/views/campgrounds/_form.html.haml
= simple_form_for @campground do |f|
  = f.input :latitude, :input_html=>{:id => 'trailhead_latitude'}, :as => :hidden
  = f.input :longitude, :input_html=>{:id => 'trailhead_longitude'}, :as => :hidden
  #trailhead-meta
    %label.text-attr-label.address{:for => "id_start_address"}
      Reposition the map by entering an address or location here:
    %input#id_start_address{:placeholder => "Address or location", :type => "text"}/
    %a#find_address.green-button.right{:href => "#"}
      Go  
    = f.input :name, :placeholder => "Simple and descriptive", :label => "Name the campground"
    %label.text-attr-label Description
    .editor
      %textarea(name="campground[description]" id="campground_description" rows="10" cols="40")
        #{@campground.description}
  / e: tour
  #plan-map-instructions Click on the map to place your campground. You can reposition your pin by dragging it or clicking in a new location. Gray pins show existing campgrounds.
  #plan-map
  .attributes
    #trailhead-features
      Attributes available at this campground:
    / = f.association :trailhead_features, :as => :check_boxes
    %ul.outer-list
      - Category.order('rank').each do |category|
        - unless category.campground_features.empty?
          %li
            %label.text-attr-label
              #{ category.name }
            %ul
              - category.campground_features.each_with_index do |attribute,index|
                - if index >= 5
                  - extra_class = "hidden"
                %li(class="#{extra_class}")
                  %label{:for => "campground[campground_features[#{attribute.id}]"}
                    - if @campground.campground_features.include? attribute
                      %input(type="checkbox" name="campground[campground_feature_ids][]"
                        id="campground_campground_feature_ids_#{attribute.id}"
                        value="#{attribute.id}"
                        checked="checked")
                    - else
                      %input(type="checkbox" name="campground[campground_feature_ids][]"
                        id="campground_campground_feature_ids_#{attribute.id}"
                        value="#{attribute.id}")
                    #{ attribute.name }
              - if category.campground_features.count >= 5
                %a.show-more{:href => "#"} + show more..

      - if current_user.admin?
        %li
          = f.input :approved
      %li
        %input.green-link-button{:type => "submit", :value => "Save Campground"}
      %li
        %input#cancel-button.dark-gray-link-button{"data-url" => "/", :type => "button", :value => "Cancel"}

      / attributes
  / e: plan
/ e: page
%script{:src => "/assets/legacy/pointmap.js", :type => "text/javascript"}
:javascript
  $(function() {
      editMode = #{  @campground.new_record? ? "TNT.EditMode.NEW;" : "TNT.EditMode.UPDATE;" }
      CKEDITOR.replace('campground_description',
              {
                  toolbar:'Basic'
              });

      $('a.show-more').toggle(function(e) {
          e.preventDefault();
          $(this).parent().find('li.hidden').show().slideDown();
          $(this).text('- show less');
      },function(e) {
          e.preventDefault();
          $(this).parent().find('li.hidden').hide().slideUp();
          $(this).text('+ show more');
      });

      initEditing(TNT.EntityType.CAMPGROUND, editMode);

      $(window).unload(function () {
          GUnload();
      });

      $('#find_address').click(function(e){
          e.preventDefault();
          findAddress(editMode);
      });

      $('#id_start_address').bind('keypress',function(e){
          var code = (e.keyCode ? e.keyCode : e.which);
          if(code == 13) { //Enter keycode
              //Do something
              e.preventDefault();
              findAddress(editMode);
          }
      });

      $('ul.outer-list ul li:odd').css({backgroundColor: '#F6F7FC'});

      $('#cancel-button').click(function(e){
          e.preventDefault();
          window.location.href = $(this).data('url');
      });
  });

app/views/campgrounds/edit.html.haml
- content_for :head do
  = javascript_include_tag "//maps.googleapis.com/maps/api/js?key=AIzaSyCcUhpQftpOwXVSLJqHrvwYCqnhTy3bchE&sensor=false&libraries=places"
  = javascript_include_tag "legacy/markermanager"
  = render :partial => "/shared/partials/legacy_head"
  = stylesheet_link_tag "editors"

#page
  #page-head
    %h2
      Edit Campground
    %a{:href => "/"} Back to Map
  / e: page head
  #plan.alt.trailhead

    = render 'form'

app/views/campgrounds/index.html.haml
%h1 Listing campgrounds

%table
  %tr
    %th Name
    %th Description
    %th Latitude
    %th Longitude
    %th User
    %th Park
    %th Approved
    %th
    %th
    %th

  - @campgrounds.each do |campground|
    %tr
      %td= campground.name
      %td= campground.description
      %td= campground.latitude
      %td= campground.longitude
      %td= campground.user
      %td= campground.park
      %td= campground.approved
      %td= link_to 'Show', campground
      %td= link_to 'Edit', edit_campground_path(campground)
      %td= link_to 'Destroy', campground, :data => { :confirm => 'Are you sure?' }, :method => :delete

%br

= link_to 'New Campground', new_campground_path

app/views/campgrounds/info_window.html.haml
/ the point variable here is a Campground object
.trailhead-info-window
  .trailhead-info-window-title #{ @point.name }
  - if @point.default_park
    .trailhead-info-window-park
      %i
        #{ @point.default_park.name }
      - if @point.default_park.county
        \-
        %i #{ @point.default_park.county }
  - if @point.description
    %p.trailhead-info-window-description
      != truncate_html(@point.description, :limit => 200, :omission => "...")

  - if @feature_names
    %p
      %b Features
      \:
      #{ @feature_names }
      / - unless @trips.empty?
      /   %h4 Trips
      /   %ul
      /     - @trips.each do |trip|
      /       %li
      /         %a{:href => "/trips/#{ trip.id }"}
      /           #{ trip.name }
  %p
    .trailhead-info-window-buttons
      %a{:href => "/campgrounds/#{ @point.id }"} Details
      |
      %a{:href => "/plan/campground/#{ @point.id }"} Plan

  - if current_user && current_user.admin?
    %p
      %b Actions
      %ul
        %li
          %a{:href => "#{edit_campground_path(@point)}"} Edit
        %li
          = link_to("Delete", @point, :method => :delete, :confirm => "Are you sure?")

app/views/campgrounds/new.html.haml
- content_for :head do
  = javascript_include_tag "//maps.googleapis.com/maps/api/js?key=AIzaSyCcUhpQftpOwXVSLJqHrvwYCqnhTy3bchE&sensor=false&libraries=places"
  = javascript_include_tag "legacy/markermanager"

  = render :partial => "/shared/partials/legacy_head"

  = stylesheet_link_tag "legacy/reset"
  = stylesheet_link_tag "editors"

#page
  #page-head
    %h2
      New Campground
    %a{:href => "/"} Back to Map
  / e: page head
  #plan.alt.trailhead

    = render 'form'

app/views/campgrounds/show.html.haml
- content_for :title do
  Transit & Trails : #{@campground.name}

- content_for :head do
  = javascript_include_tag "//maps.googleapis.com/maps/api/js?key=AIzaSyCcUhpQftpOwXVSLJqHrvwYCqnhTy3bchE&sensor=false&libraries=places"
  = javascript_include_tag "legacy/markermanager"

  / load Galleria
  %script{:src => "/assets/legacy/galleria/galleria-1.2.7.min.js"}
  = javascript_include_tag "legacy/common"

  = stylesheet_link_tag "legacy/legacy"
  = stylesheet_link_tag "legacy/trailhead_detail"

/ begin lightboxed images
- @campground.photos.each_with_index do |photo,i|
  .overlay{:id => "photo#{i}"}
    %div
      %a{:href => "//flickr.com/photos/transitandtrails/#{photo.flickr_id}", :target => "_blank"}
        %img.thumbnail{:src => "#{photo.flickr_medium_url}"}/
/ end lightboxed images

#page.trip-details.legacy

  #details-section
    #plan.alt.trailhead
      #page-head
        %h2 Campground
        = link_to "BACK TO MAP", find_campgrounds_path
      / e: page head
      #trip-meta
        / begin share widgets
        .trailhead-social-buttons
          .share-widget
            %a.twitter-share-button{"data-count" => "none", "data-url" => "#{campground_path(@campground)}", "data-via" => "transitandtrail", :href => "https://twitter.com/share"} Tweet
            %script{:src => "//platform.twitter.com/widgets.js", :type => "text/javascript"}
          .share-widget
            %iframe{:allowTransparency => "true", :frameborder => "0", :scrolling => "no", :src => "//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.transitandtrails.org%2Fcampgrounds%2F#{@campground.id}&send=false&layout=button_count&width=450&show_faces=false&action=like&colorscheme=light&font&height=80&appId=173296509398219", :style => "border:none; overflow:hidden; width:52px; height:21px;"}
        / end share widgets
        .header
          %h2 #{@campground.name}
          %img.type-flag{:alt => "", :src => "/assets/legacy/campground.png"}/
          - if @campground.default_park
            %em
            %a{:href => "#{park_path(@campground.default_park)}"} #{@campground.default_park.name}
        / b:details
        #trailhead-details
          - if @campground.description
            .description
              .short-description
                != truncate_html(@campground.description, :length=> 400,  :omission => " ...<p><br/><a id='more-desc-link' class='read-more-less-link' href='#'>Read more &raquo;</a></p>")
              .full-description
                != @campground.description
                %br
                = link_to "#", id: "less-desc-link", class: "read-more-less-link" do
                  &laquo; Read Less
          - else
            %div{:style => "height:10px"}

          = render :partial => "/shared/partials/features", :locals => {:object=>@campground}

          .button-frame

            %a.green-button.padded-sides{:href => "/plan/campground/#{@campground.id}"}
              Plan Trip to Here

          - if can?(:edit,@campground)
            .button-frame
              %a.green-button{:href => "#{edit_campground_path(@campground)}"} Edit Campground

          - if can?(:destroy,@campground)
            .button-frame
              = link_to("Delete Campground", @campground, :method => :delete, :confirm => "Are you sure?", :class=>"green-button")

          = render :partial => "/shared/partials/object_maps", :locals => {:object=>@campground}

        = render :partial => "/shared/partials/agency", :locals => {:object=>@campground}

        / - regional_trails = @campground.campground_features.where(:category_id=>Category.where(:name=>"Regional Trail"))
        / - regional_trails.each do |feature|
        /   - klass = feature == regional_trails.last ? "agency last" : "agency"
        /   .if.endif{:class => "#{klass}"}
        /     .logo
        /       - if feature.marker_icon
        /         - if feature.link_url
        /           %a{:href => "#{feature.link_url}", :target => "_blank"}
        /             %img{:src => "#{feature.marker_icon.url}"}/
        /         - else
        /           %img{:src => "#{feature.marker_icon.url}"}/
        /     .text
        /       This trail is part of the
        /       .name
        /         - if feature.link_url
        /           %a{:href => "#{feature.link_url}", :target => "_blank"}
        /             #{ feature.name }
        /         - else
        /           #{feature.name}

        = render :partial => "/shared/partials/non_profit_partner", :locals => {:object=>@campground}

    / e:plan
    = render :partial => "/shared/partials/object_stories", :locals => {:object=>@campground}

  #trailhead-photos-map
    = render :partial => "/shared/partials/object_photos", :locals => {:object=>@campground}
    .section-head
      %h2 Map
    #plan-map.trailhead-details-map
    #trailhead-comments
      .section-head
        %h2 Comments
      / e: page head
      .comments
        = render :partial => "/shared/partials/disqus"
    / e: comments
  .clearfix  

%script{:src => "/assets/legacy/pointmap.js", :type => "text/javascript"}
%script{:src => "/assets/legacy/jquery/js/jquery.tools.min.js", :type => "text/javascript"}

:javascript
  $(document).ready(function(){
      $(".scrollable").scrollable({circular:false});
      $(".photo img[rel]").overlay();

      if ($('#galleria').get(0)) {
          Galleria.loadTheme('/assets/legacy/galleria/galleria.classic.min.js');
          // Initialize Galleria
          Galleria.configure({thumbnails:false, imageMargin:0, imageCrop:true});
          Galleria.run('#galleria');

          Galleria.ready(function(){

          });
      }

      $('thumbnail a[rel]').overlay();

      initCampgroundDetails(#{@campground.id}, false);

      $(window).unload(function () {
          GUnload();
      });

      $('input:radio[name=map-select]').click(function () {
          if ($('input:radio[name=map-select]:checked').val() == "url") {
              $('#map-save-button').attr('value', "Save");
              $('#map_url').show();
              $('#map').hide();
          } else if ($('input:radio[name=map-select]:checked').val() == "file") {
              $('#map-save-button').attr('value', "Upload");
              $('#map_url').hide();
              $('#map').show();
          }
      });
  });